### ISSUE TITLE
Error: Cannot find module 'multi-hashing'

### ISSUE THREAD

**Issue by KhmerRun** [italocoin-project/italocoin-pool#1]
I got this error during node init.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'multi-hashing'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by italocoin-project** [comment]
Did you used node 0.10.48? Did you hit npm update? What are the compilation steps you made?

**Comment by KhmerRun** [comment]
version: v0.10.25
npm update
Edit config.json to suit my needs.
screen node init.js

**Comment by italocoin-project** [comment]
Try with node 0.10.48, do you get any error durring npm update?
