### ISSUE TITLE
Pool not process with payments

### ISSUE THREAD

**Issue by KhmerRun** [italocoin-project/italocoin-pool#2]
Hello,

I just run a small pool yesterday and found some blocks but the pool didn't process any payment. Logs as below:

2018-04-21 06:26:13 [payments] Error with send_transaction RPC request to wallet daemon {}
2018-04-21 06:26:13 [payments] Payments failed to send to {"amount":34800000000000,"address":"XXXXXX"}
2018-04-21 06:26:13 [payments] Payments splintered and 0 successfully sent, 1 failed

And in wallet RPC, I saw it received for block rewards already. The config.json is by default and I change only diff ports.

**Comment by italocoin-project** [comment]
Hi,

Did you started rpc wallet bidding on the port that is in pool config?

**Comment by KhmerRun** [comment]
Hello,

RPC Wallet:
screen ./italocoin-wallet-rpc --wallet-file ItaloCoinPool --password xxxxx --rpc-bind-port 8082

config.json:
    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },

**Comment by italocoin-project** [comment]
You need to run rpc like this 
./italocoin-wallet-rpc --disable-rpc-login --trusted-daemon --rpc-bind-port 8082 --wallet-file MINER --password PASSWORD

**Comment by KhmerRun** [comment]
Hi,

Thanks, after using that, I could see the wallet rpc sent payment immediately and listed in explorer of italocoin.

When I checked in my mined wallet, it is still empty with zero balance though explorer number of confirmations already reached 100+. Already tried with rescan_bc.

**Comment by italocoin-project** [comment]
Are you using GUI wallet? If so check this tweet https://twitter.com/italocoin/status/986325110004092930

**Comment by KhmerRun** [comment]
Hi, I use Linux cli wallet.

**Comment by italocoin-project** [comment]
Did you downloaded our latest release? We did a hardfork 4 days ago. Did you removed the old blockchain? And resync from 0?

**Comment by KhmerRun** [comment]
Hi,

I downloaded and compile on 20th which was yesterday and started sync from that yesterday also.

'Lithium Luna' (v0.12.0.0-master-release)

**Comment by KhmerRun** [comment]
This is in explorer:

https://explorer.italocoin.com/tx/a0a56986b625231fdd47d3a71b976e6011ff864884bc68630c048e42851ad421#blockchain_transaction

**Comment by italocoin-project** [comment]
That's really weird, try to regenerate the wallet with mnemonic seed,  did you got any warnings or error's during sync?

**Comment by KhmerRun** [comment]
Hi, I just re-generate using seed and the transaction coming in. It is OK now until generating it new by seed.

**Comment by italocoin-project** [comment]
Hm, i need to investigate this.

**Comment by KhmerRun** [comment]
Hello, if you need any information on this, i could assist to provide.

**Comment by KhmerRun** [comment]
I think this one may be the issue with original cryptonote or something. SolaceCoin also had the same issue and I got balance by re-generating from seed.

**Comment by italocoin-project** [comment]
I found the problem, monero has the same issue, it's because you are not syncing on the correct chain, i'm looking into it to solve this problem on the next release, monero is already pushing ideas to solve this problem, read more here https://github.com/monero-project/monero/issues/3661#issuecomment-383327841
