### ISSUE TITLE
ita.minexmr24.ru

### ISSUE THREAD

**Issue by swa74** [italocoin-project/italocoin-pool#3]
Good afternoon.
He installed the pool, he found the block, there are no mistakes, writes that a reward of 8.7341 coins was received, but coins did not come to the purse of the pool.
With what this problem can be connected?
![default](https://user-images.githubusercontent.com/34404806/39662137-e909735e-5065-11e8-895b-e96772909abf.JPG)
![1](https://user-images.githubusercontent.com/34404806/39662138-ed3a9890-5065-11e8-8896-c568a19f7067.JPG)
![2](https://user-images.githubusercontent.com/34404806/39662140-f089974e-5065-11e8-9f69-2020b32ac75c.JPG)
![3](https://user-images.githubusercontent.com/34404806/39662142-f2f40564-5065-11e8-8ce6-4686d3d3ab56.JPG)
![4](https://user-images.githubusercontent.com/34404806/39662144-f5761156-5065-11e8-83f3-4aad93b1bcbc.JPG)

http://ita.minexmr24.ru

**Comment by italocoin-project** [comment]
Hello, please regenerate the wallet with mnemonic seed, i will fix this problem within the next hardfork, follow this steps https://bitcointalk.org/index.php?topic=3122277.msg32312322#msg32312322

**Comment by swa74** [comment]
Thanks, now I'll try. Based on the results otpishus.
If you have a list of your coin pools, can you add my pool to it?

**Comment by swa74** [comment]
Thanks, helped
Will we cooperate?
