### ISSUE TITLE
nodejs-pool

### ISSUE THREAD

**Issue by swa74** [italocoin-project/italocoin-pool#5]
Have not you tried to make a pool like this?
https://github.com/Snipa22/nodejs-pool

**Comment by italocoin-project** [comment]
Hello,

i haven't because the current pool.italocoin.com pool works really well. And as far as i know nodejs-pool uses mysql wich i don't like, in speed is way slower than redis and eats way more resources.

**Comment by swa74** [comment]
Well, thought could have tried

**Comment by italocoin-project** [comment]
I will try it out, but now i'm really bussy. I will keep you posted when i test it.
